---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	support_handler(support_handler)
	suggestion_handler(suggestion_handler)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	router -. &nbsp;suggestion&nbsp; .-> suggestion_handler;
	router -. &nbsp;support&nbsp; .-> support_handler;
	suggestion_handler --> __end__;
	support_handler --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
